services:
  - type: web
    name: orange-money-api
    env: node
    region: oregon
    plan: free
    rootDir: orange-money-production
    buildCommand: npm install
    startCommand: npm run production
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      # Required - set these in Render Dashboard with real values
      - key: ORANGE_CLIENT_ID
        value: "REPLACE_ME"
      - key: ORANGE_CLIENT_SECRET
        value: "REPLACE_ME"
      - key: ORANGE_MERCHANT_KEY
        value: "REPLACE_ME"
      # Optional - if provided by Orange Money
      - key: ORANGE_APPLICATION_ID
        value: ""
      # Orange Money endpoints (keep defaults or adjust for your region)
      - key: ORANGE_TOKEN_URL
        value: https://api.orange.com/oauth/v3/token
      - key: ORANGE_PAYMENT_URL
        value: https://api.orange.com/orange-money-webpay/gn/v1/webpayment
      # Domains for redirects and webhooks
      - key: FRONTEND_DOMAIN
        value: https://dreamexdatalab.com
      - key: API_DOMAIN
        value: https://api.dreamexdatalab.com
      - key: DOMAIN
        value: https://api.dreamexdatalab.com
      # Rate limit defaults
      - key: RATE_LIMIT_WINDOW
        value: "900000" # 15 minutes in ms
      - key: RATE_LIMIT_MAX
        value: "100"